name: Build for Linux

on:
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Qt and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            qtbase5-dev \
            qtbase5-private-dev \
            qtdeclarative5-dev \
            qttools5-dev

      - name: Create build directory
        run: |
          rm -rf build
          mkdir build
          echo "BUILD_DIR=$(pwd)/build" >> $GITHUB_ENV

      - name: Configure CMake
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

      - name: Build
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          cmake --build . -- -j$(nproc)

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: geopter-gui
          path: ${{ github.workspace }}/bin/geopter-gui
